# Generated by Django 5.1.3 on 2025-05-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='book_id',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Kitob id'),
        ),
    ]
