# Generated by Django 5.1.3 on 2025-05-22 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0002_bookmodel_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='preordermodel',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preorder', to='havasbook.deliverymodel'),
        ),
        migrations.AddField(
            model_name='preordermodel',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preorder', to='havasbook.locationmodel'),
            preserve_default=False,
        ),
    ]
