# Generated by Django 5.1.3 on 2025-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0003_preordermodel_delivery_method_preordermodel_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preordermodel',
            old_name='user_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='preordermodel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqt pul'), ('click', 'Click'), ('payme', 'Payme'), ('paynet', 'Paynet'), ('uzum_card', 'Uzum karta')], default='click', max_length=50, verbose_name="To'lov turi"),
        ),
    ]
