# Generated by Django 5.1.3 on 2025-05-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0004_rename_user_name_preordermodel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preordermodel',
            old_name='name',
            new_name='reciever_name',
        ),
        migrations.RenameField(
            model_name='preordermodel',
            old_name='phone',
            new_name='reciever_phone',
        ),
    ]
