# Generated by Django 5.1.3 on 2025-05-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0005_rename_name_preordermodel_reciever_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='product_type',
            field=models.CharField(choices=[('book', 'Kitob'), ('clothes', 'Kiyim'), ('technique', 'Texnika'), ('other', 'Boshqalar')], default='book', max_length=50, verbose_name='Mahsulot turi'),
        ),
    ]
