# Generated by Django 5.1.3 on 2025-05-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0007_auto_20250522_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationmodel',
            name='title_kril',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='title_uz',
        ),
    ]
