# Generated by Django 5.1.3 on 2025-05-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0007_auto_20250522_1544'),
        ('havasbook', '0007_auto_20250522_1549'),
    ]

    operations = [
    ]
