# Generated by Django 5.1.3 on 2025-05-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0008_remove_locationmodel_title_kril_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_type',
            field=models.CharField(choices=[('order', 'Oddiy buyurtma'), ('preorder', 'Oldindan buyurtma')], default='order', max_length=100, verbose_name='Buyurtma turi'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_method',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('paynet', 'Paynet'), ('uzum_card', 'Uzum karta')], default='click', max_length=50, verbose_name="To'lov turi"),
        ),
    ]
