# Generated by Django 5.1.3 on 2025-05-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0008_merge_0007_auto_20250522_1544_0007_auto_20250522_1549'),
        ('havasbook', '0009_ordermodel_order_type_and_more'),
    ]

    operations = [
    ]
