# Generated by Django 5.1.3 on 2025-05-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0010_merge_20250523_1521'),
    ]

    operations = [
    ]
