# Generated by Django 5.1.3 on 2025-05-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0011_auto_20250523_1526'),
    ]

    operations = [
    ]
