# Generated by Django 5.1.3 on 2025-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0012_auto_20250523_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='original_price_kril',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Asl narxi'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='original_price_ru',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Asl narxi'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='original_price_uz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Asl narxi'),
        ),
    ]
