# Generated by Django 5.1.3 on 2025-06-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0013_bookmodel_original_price_kril_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='original_price_kril',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='original_price_ru',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='original_price_uz',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='base_currency',
            field=models.CharField(choices=[('USD', '$'), ('UZS', 'uzs'), ('RUB', '₽')], default='USD', max_length=3, verbose_name='Asosiy valyuta'),
        ),
    ]
