# Generated by Django 5.1.3 on 2025-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0014_remove_bookmodel_original_price_kril_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='product_type',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkaklar uchun'), ('female', 'Ayollar uchun'), ('unisex', 'Ikkalasiga ham')], default='unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='base_currency',
            field=models.CharField(choices=[('USD', '$'), ('UZS', "so'm"), ('RUB', '₽'), ('EUR', '€')], default='USD', max_length=3, verbose_name='Asosiy valyuta'),
        ),
    ]
