# Generated by Django 5.1.3 on 2025-06-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0015_remove_bookmodel_product_type_bookmodel_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'BrandModel',
                'verbose_name_plural': 'BrandModels',
                'db_table': 'brand',
            },
        ),
    ]
