# Generated by Django 5.1.3 on 2025-06-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0016_brandmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('male', 'Erkaklar uchun'), ('female', 'Ayollar uchun')], default='male', max_length=255, verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'GenderModel',
                'verbose_name_plural': 'GenderModels',
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='SubcategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'SubcategoryModel',
                'verbose_name_plural': 'SubcategoryModels',
                'db_table': 'subcategory',
            },
        ),
    ]
