# Generated by Django 5.1.3 on 2025-06-19 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0017_gendermodel_subcategorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.brandmodel', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.subcategorymodel', verbose_name='SubCategory'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.brandmodel', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.gendermodel', verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.categorymodel', verbose_name='Cateogry'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='havasbook.subcategorymodel'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.gendermodel', verbose_name='Gemder'),
        ),
    ]
