# Generated by Django 5.1.3 on 2025-06-19 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0018_bookmodel_brand_bookmodel_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='havasbook.categorymodel'),
        ),
        migrations.AddField(
            model_name='gendermodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.gendermodel', verbose_name='Gender'),
        ),
    ]
