# Generated by Django 5.1.3 on 2025-06-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0019_categorymodel_parent_gendermodel_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategorymodel',
            name='parent',
        ),
    ]
