# Generated by Django 5.1.3 on 2025-06-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0020_remove_categorymodel_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gendermodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.gendermodel'),
        ),
        migrations.AlterField(
            model_name='gendermodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkaklar uchun'), ('female', 'Ayollar uchun'), ('unisex', 'Hammasi uchun')], default='male', max_length=255, verbose_name='Gender'),
        ),
    ]
