# Generated by Django 5.1.3 on 2025-06-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0021_remove_gendermodel_slug_brandmodel_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
    ]
