# Generated by Django 5.1.3 on 2025-06-30 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0022_brandmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.categorymodel', verbose_name='Category'),
        ),
    ]
