# Generated by Django 5.1.3 on 2025-07-07 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0023_brandmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='base_currency',
            field=models.CharField(choices=[('USD', '$'), ('UZS', "so'm"), ('RUB', '₽'), ('EUR', '€')], default='USD', max_length=3, verbose_name='Основная валюта'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='book_id',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='ID продукта'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.brandmodel', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='havasbook.categorymodel', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='color',
            field=models.ManyToManyField(blank=True, to='havasbook.colormodel', verbose_name='Цвет продукта'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='description_kril',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.gendermodel', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book-image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name='Есть ли скидка?'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='is_preorder',
            field=models.BooleanField(default=False, verbose_name='Предзаказ доступен?'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='name_kril',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Исходная цена'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Популярный?'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество продукта'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='size',
            field=models.ManyToManyField(blank=True, to='havasbook.sizemodel', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество продаж'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.subcategorymodel', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
