# Generated by Django 5.1.3 on 2025-07-07 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0024_alter_bookmodel_base_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookimagemodel',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='cartitemmodel',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='deliverymodel',
            options={'verbose_name': 'Способ доставки', 'verbose_name_plural': 'Способы доставки'},
        ),
        migrations.AlterModelOptions(
            name='gendermodel',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Полы'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='orderitemmodel',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='organizationmodel',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='preordermodel',
            options={'verbose_name': 'Предзаказ', 'verbose_name_plural': 'Предзаказы'},
        ),
        migrations.AlterModelOptions(
            name='productsimagemodel',
            options={'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображения продукта'},
        ),
        migrations.AlterModelOptions(
            name='productsmodel',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='sizemodel',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='subcategorymodel',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='image',
            field=models.ImageField(upload_to='banner-image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bookimagemodel',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='havasbook.bookmodel', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='bookimagemodel',
            name='image',
            field=models.ImageField(upload_to='book-image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='base_currency',
            field=models.CharField(choices=[('USD', 'Доллар США ($)'), ('UZS', 'Сум (UZS)'), ('RUB', 'Рубль (₽)'), ('EUR', 'Евро (€)')], default='USD', max_length=3, verbose_name='Основная валюта'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='book_id',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='ID товара'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='color',
            field=models.ManyToManyField(blank=True, to='havasbook.colormodel', verbose_name='Цвет товара'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='description_kril',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Процент скидки (%)'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name='Есть скидка?'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='is_preorder',
            field=models.BooleanField(default=False, verbose_name='Доступен предзаказ?'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Продано (шт.)'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.categorymodel', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.gendermodel', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(upload_to='category-image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name_kril',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='image',
            field=models.ImageField(upload_to='book-color/', verbose_name='Изображение цвета'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='name_kril',
            field=models.CharField(max_length=50, null=True, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='title',
            field=models.CharField(verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='title_kril',
            field=models.CharField(null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='title_uz',
            field=models.CharField(null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='title_kril',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gendermodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Для мужчин'), ('female', 'Для женщин'), ('unisex', 'Для всех')], default='male', max_length=255, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='long',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_type',
            field=models.CharField(choices=[('order', 'Обычный заказ'), ('preorder', 'Предзаказ')], default='order', max_length=100, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_method',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('paynet', 'Paynet'), ('uzum_card', 'Карта Uzum')], default='click', max_length=50, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='reciever_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='reciever_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='new', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='bot_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Токен бота'),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='preordermodel',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='preordermodel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('click', 'Click'), ('payme', 'Payme'), ('paynet', 'Paynet'), ('uzum_card', 'Карта Uzum')], default='click', max_length=50, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='preordermodel',
            name='reciever_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='preordermodel',
            name='reciever_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='preordermodel',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='preordermodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='productsimagemodel',
            name='image',
            field=models.ImageField(upload_to='product-image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productsimagemodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='havasbook.productsmodel', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='havasbook.categorymodel', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='description_kril',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product-image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name='Есть ли скидка?'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='is_preorder',
            field=models.BooleanField(default=False, verbose_name='Доступен предзаказ?'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='name_kril',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Исходная цена'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество продаж'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название размера'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='name_kril',
            field=models.CharField(max_length=255, null=True, verbose_name='Название размера'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название размера'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название размера'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='title',
            field=models.CharField(verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='title_kril',
            field=models.CharField(null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='title_uz',
            field=models.CharField(null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='havasbook.categorymodel', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterModelTable(
            name='orderitemmodel',
            table='orderItem',
        ),
    ]
