# Generated by Django 5.1.3 on 2025-07-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0025_alter_bookimagemodel_options_alter_bookmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='title_en',
            field=models.CharField(null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='sizemodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название размера'),
        ),
        migrations.AddField(
            model_name='sizemodel',
            name='title_en',
            field=models.CharField(null=True, verbose_name='Размер'),
        ),
    ]
