# Generated by Django 5.1.3 on 2025-08-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('havasbook', '0026_bookmodel_description_en_bookmodel_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='brandmodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='gender',
        ),
    ]
